from .interface import IPipeline
from src.util.goal import ForecastingGoal
from .ar_linear_regression import Use_ARLinearRegression
from .ar_rbf_svr import Use_ARSupportVectorRegressionRBF
from .ar_linear_svr import Use_ARSupportVectorRegressionLinear
from .ar_cnn_nn import Use_ARConvolutionalNeuralNetwork
from .ar_lstm_nn import Use_ARLongShortTermMemoryNeuralNetwork
from .ar_mlp_nn import Use_ARMultiLayerPerceptronNeuralNetwork